download_url: "https://raw.githubusercontent.com/ageron/handson-ml/master/datasets/housing/housing.tgz"
raw_data_path: "data/"
raw_data_file: "housing.csv"
linear_regression: "artifacts/model/lr_model.pkl"
decision_tree: "artifacts/model/dt_model.pkl"
random_forest_random_search: "artifacts/model/rf_rs_model.pkl"
random_forest_grid_search: "artifacts/model/rf_gs_model.pkl"
test_size: 0.2
splits: 1
model_monitoring_path: "artifacts/reports/evidently/"
target : "median_house_value"
final_model : "random_forest_grid_search"